# sync_frequency = "1m"

style = "compact"
inline_height = 0

history_filter = [
   "^cd",
   "^z",
   "^ls",
   "^exit",
   "^e",
   "^clear",
   "^htop",
   "^tgpt",
   "^zellij"
]

enter_accept = true

[theme]
name = "catppuccin-mocha"
