sync_address = "http://192.168.1.82"
sync_frequency = "1m"

style = "compact"

history_filter = [
   "^cd",
   "^z",
   "^ls",
   "^exit",
   "^e",
   "^clear",
   "^htop",
   "^tgpt",
   "^zellij"
]

enter_accept = true
